#!/usr/bin/env bash
# shellcheck disable=SC1091
# shellcheck disable=SC2016

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'

run docker buildx bake --push image-all

# image_id="$(docker images --filter=reference=rtorrent-rutorrent --format "{{.ID}}")"
# run docker image tag "${image_id}" jrgoodle/rtorrent-rutorrent:latest
# run docker image push jrgoodle/rtorrent-rutorrent:latest
