name: builder-ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Tag output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            "${{ secrets.DOCKER_USERNAME }}/rutorrent:latest"
            "${{ secrets.DOCKER_USERNAME }}/rutorrent:${{ steps.vars.outputs.tag }}"
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/rutorrent:amd64-latest"
          platforms: linux/arm64
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/rutorrent:arm64v8-latest"
          platforms: linux/arm/v7
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/rutorrent:arm32v7-latest"
