name: builder-ci

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Preparation Stage
        id: prep
        run: |
          echo ::set-output name=image::${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
          echo ::set-output name=gittag::${GITHUB_REF#refs/*/}
          echo ::set-output name=created::"org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Image & Push arm32v7
        run: |
          docker buildx build \
          --label ${{ steps.prep.outputs.created }} \
          -t "${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.gittag }}-arm32v7" \
          -t "${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.gittag }}" \
          -t "${{ steps.prep.outputs.image }}:arm32v7-latest" \
          -t "${{ steps.prep.outputs.image }}:latest" \
          --platform linux/arm/v7 -f ./Dockerfile.armhf \
          --push .
      -
        name: Build Image & Push arm64v8
        run: |
          docker buildx build \
          --label ${{ steps.prep.outputs.created }} \
          -t "${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.gittag }}-arm64v8" \
          -t "${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.gittag }}" \
          -t "${{ steps.prep.outputs.image }}:arm64v8-latest" \
          -t "${{ steps.prep.outputs.image }}:latest" \
          --platform linux/arm64 -f ./Dockerfile.arm64 \
          --push .
      -
        name: Build Image & Push amd64
        run: |
          docker buildx build \
          --label ${{ steps.prep.outputs.created }} \
          -t "${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.gittag }}-amd64 " \
          -t "${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.gittag }}" \
          -t "${{ steps.prep.outputs.image }}:amd64-latest" \
          -t "${{ steps.prep.outputs.image }}:latest" \
          --platform linux/amd64 -f ./Dockerfile \
          --push .
