name: builder-ci

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Preparation Stage
        id: prep
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/rutorrent
          SOURCE=${IMAGE}
          echo ::set-output name=gittag::${GITHUB_REF#refs/*/}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build arm32v7 Image & Push
        run: |
          docker buildx build --label org.opencontainers.image.created=${{ steps.prep.outputs.created }} -t "${SOURCE}:arm32v7-latest" --platform linux/arm/v7 --file ./Dockerfile.armhf --push .
