name: testbuild-ci

on:
  push:
    tags:
      - 'test*'

env:
  DOCKERHUB_SLUG: xxacielxx/rutorrent

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Generate Image Labels
        id: leb
        run: |
          echo "gittag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "version=org.opencontainers.image.version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "revision=org.opencontainers.image.revision=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "created=org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build Image & Push
        run: |
          docker buildx build \
          --label ${{ steps.leb.outputs.version }} \
          --label ${{ steps.leb.outputs.revision }} \
          --label ${{ steps.leb.outputs.created }} \
          -t "${{ env.DOCKERHUB_SLUG }}:${{ steps.leb.outputs.gittag }}" \
          --platform linux/amd64,linux/arm/v7,linux/arm64 -f ./Dockerfile --push .
