name: testbuild-ci

on:
  push:
    tags:
      - 'test*'
    paths-ignore:
      - '**.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Preparation Stage
        id: prep
        run: |
          echo ::set-output name=image::${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
          echo ::set-output name=gittag::${GITHUB_REF#refs/*/}
      -
        name: Labels Stage
        id: leb
        run: |
          echo ::set-output name=version::org.opencontainers.image.version=${{ steps.prep.outputs.gittag }}
          echo ::set-output name=revision::org.opencontainers.image.revision=${GITHUB_SHA}
          echo ::set-output name=created::org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build Image & Push
        run: |
          docker buildx build --no-cache --pull \
          --label ${{ steps.leb.outputs.created }} --label ${{ steps.leb.outputs.version }} --label ${{ steps.leb.outputs.revision }} \
          -t "${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.gittag }}" \
          --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -f ./Dockerfile --push .
