name: testbuild-ci

on:
  push:
    tags:
      - 'test*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Preparation Stage
        id: prep
        run: |
          echo ::set-output name=image::${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
          echo ::set-output name=gittag::${GITHUB_REF#refs/*/}
      -
        name: Labels Stage
        id: leb
        run: |
          echo ::set-output name=vendor::org.opencontainers.image.vendor=XxAcielxX
          echo ::set-output name=title::org.opencontainers.image.title=ruTorrent
          echo ::set-output name=version::org.opencontainers.image.version=${{ steps.prep.outputs.gittag }}
          echo ::set-output name=revision::org.opencontainers.image.revision=${GITHUB_SHA}
          echo ::set-output name=created::org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=desc::org.opencontainers.image.description=rTorrent + ruTorrent Docker based container
          echo ::set-output name=lic::org.opencontainers.image.licenses=MIT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build Image & Push arm64v8
        run: |
          docker buildx build \
          --label ${{ steps.leb.outputs.created }} --label ${{ steps.leb.outputs.version }} --label ${{ steps.leb.outputs.revision }} \
          -t "${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.gittag }}-arm64v8" \
          --platform linux/arm64 -f ./Dockerfile.arm64 --push .
